# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

. "$HOME/.local/bin/env"

# spicetify
export PATH="$HOME/.spicetify:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
